### ISSUE TITLE
skyobject.Refs.RefByHash doesn't work as expected

### ISSUE THREAD

**Issue by logrusorgru** [skycoin/cxo#115]
Sometimes the `RefByHash` returns error instead of element.

**Comment by logrusorgru** [comment]
Here is skycoin/bbs#85

**Comment by evanlinjin** [comment]
I've wrote an example here: https://github.com/evanlinjin/cxotest/tree/master

Seems as though the problem only occurs when `skyobject.HashTableIndex` is set.

**Comment by logrusorgru** [comment]
The problem found. It will be solved next PR soon.

**Comment by logrusorgru** [comment]
@evanlinjin , thanks a lot for your example.
