### ISSUE TITLE
"root not found" errors occuring when root is present in connected cxo daemon

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/cxo#81]
There has been an abundance of "root not found" errors popping up. It happens when I connect two cxo daemons together. I would expect that one daemon will be fully aware of the roots available on the other daemon? Or is this not the case?

**Comment by logrusorgru** [comment]
A daemon send all root objects to all subscribers.
1) cxo receives a root
2) cxo collects all objects of the root (some time required)
3) cxo sends the root to all connections that subscribed to feed of the  root (some time required to collect)
The "root not found" is error of RootWalker. How you create it?

**Comment by evanlinjin** [comment]
Yup you are right, takes some time to sync.
